[build-system]
requires = ["setuptools>=77", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "skretrieval"
dynamic = ["version"]
description="The University of Saskatchewan Retrieval Framework"
readme = "README.md"
license = "MIT"
license-files = ["license.md"]
dependencies = ['numpy', 'xarray', 'scipy', 'numba', 'sasktran2>=2026.8.1', 'simpleeval', 'scikit-learn']
authors = [
    { name = "Daniel Zawada", email = "daniel.zawada@usask.ca" },
]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.optional-dependencies]
test = ["pytest>=8.3.3"]
plotting = ["matplotlib"]

[dependency-groups]
dev = ["pre-commit", "ruff"]
docs = ["sphinx", "myst-nb", "sphinx-book-theme", "sphinx-design", "matplotlib"]


[tool.setuptools_scm]
version_file = "src/skretrieval/_version.py"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
testpaths = ["tests"]

[tool.ruff]
src = ["src"]
exclude = ["tests/platforms/*"]

[tool.ruff.lint]
select = [
    "E", "F", "W", # flake8
    "B",           # flake8-bugbear
    "I",           # isort
    "ARG",         # flake8-unused-arguments
    "C4",          # flake8-comprehensions
    "EM",          # flake8-errmsg
    "ICN",         # flake8-import-conventions
    "ISC",         # flake8-implicit-str-concat
    "G",           # flake8-logging-format
    "PGH",         # pygrep-hooks
    "PIE",         # flake8-pie
    "PL",          # pylint
    "PT",          # flake8-pytest-style
    "PTH",         # flake8-use-pathlib
    "RET",         # flake8-return
    "RUF",         # Ruff-specific
    "SIM",         # flake8-simplify
    "T20",         # flake8-print
    "UP",          # pyupgrade
    "YTT",         # flake8-2020
    "EXE",         # flake8-executable
    "NPY",         # NumPy specific rules
    "PD",          # pandas-vet
]
ignore = [
    "PLR",    # Design related pylint codes
    "E501",   # Line too long
    "B905",   # Zip strict
    "PLC0415", # Import outside top-level; used for optional dependencies
]
unfixable = [
    "T20",  # Removes print statements
    "F841", # Removes unused variables
    "F401", # Removes unused imports
]
flake8-unused-arguments.ignore-variadic-names = true
isort.required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["T20", "PT009"]
"**__init__.py" = ["F401"]
