name: 'nightly'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-upload-conda:
    runs-on: ubuntu-latest

    if: github.repository == 'usask-arg/skretrieval'
    environment:
      name: conda-nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Conda build environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/conda-envs/mamba-build.yml

      - name: Build Conda package
        shell: bash -el {0}
        run: |
          conda config --set anaconda_upload yes
          conda mambabuild conda.recipe --output-folder pkgs/ --user usask-arg-nightly --token ${{ secrets.ANACONDA_TOKEN_NIGHTLY }} --no-test

      - name: Save conda package
        uses: actions/upload-artifact@v3
        with:
          name: skretrieval-conda
          path: pkgs

  build_wheel:
    name: Build Wheel
    runs-on: ubuntu-latest
    if: github.repository == 'usask-arg/skretrieval'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build tarball and wheels
        run: |
          git clean -xdf
          git restore -SW .
          python -m build

      - name: Check built artifacts
        run: |
          python -m twine check --strict dist/*
          pwd
          if [ -f dist/skretrieval-0.0.0.tar.gz ]; then
            echo "❌ INVALID VERSION NUMBER"
            exit 1
          else
            echo "✅ Looks good"
          fi
      - uses: actions/upload-artifact@v3
        with:
          name: releases
          path: dist

  upload-nightly-wheels:
    needs: build_wheel
    runs-on: ubuntu-latest
    if: github.repository == 'usask-arg/skretrieval'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist

      - name: Upload wheel
        uses: scientific-python/upload-nightly-action@6e9304f7a3a5501c6f98351537493ec898728299 # 0.3.0
        with:
          artifacts_path: dist
          anaconda_nightly_upload_organization: usask-arg-nightly
          anaconda_nightly_upload_token: ${{secrets.ANACONDA_TOKEN_NIGHTLY}}
          anaconda_nightly_upload_labels: dev
